#:schema https://raw.githubusercontent.com/umnovI/dioxus-config-schema/refs/heads/main/dioxus.schema.json

[application]
name = "hypha"
default_platform = "desktop"

[web.watcher]

[web.app]

[web.resource]
style = []
script = []

[web.resource.dev]
script = []
